# Shell variables
# Generated by 'wal'
wallpaper='/home/graeme/.config/qtile/wallpapers/284466.jpg'

# Special
background='#131a17'
foreground='#cadeea'
cursor='#cadeea'

# Colors
color0='#131a17'
color1='#699AAA'
color2='#6FA1CF'
color3='#7BC1D2'
color4='#929FA8'
color5='#C5C2B1'
color6='#92B2D3'
color7='#cadeea'
color8='#8d9ba3'
color9='#699AAA'
color10='#6FA1CF'
color11='#7BC1D2'
color12='#929FA8'
color13='#C5C2B1'
color14='#92B2D3'
color15='#cadeea'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
